version: '3.3'

networks:
  todos:
    driver: bridge

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb-composed
    environment:
      MYSQL_ROOT_PASSWORD: rickele12
      MYSQL_DATABASE: todo
      
    command: --pid-file=/var/run/mysqld/mysqld.pid
    networks:
      - todos




  backend:
    build: 
      context: ./demo
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/todo
    depends_on:
      - mysqldb
    networks:
      - todos


  frontend: 
    build: 
      context: ./Frontend/VS/react-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - todos

