version: '3.3'


services:
  mysqldb:
    image: mysql:8.0
    ports: 
     - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: rickele12
      MYSQL_DATABASE: todo
      



  backend:
    image: backend:v0.1
    build: 
      context: ./demo
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3307/todo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rickele12
    depends_on:
      - mysqldb



  frontend: 
    build: 
      context: ./Frontend/VS/react-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

