version: '3.1'

services:

  postgresdb:
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=matthias
      - POSTGRES_DB=mydb
  backend: 
    build: 
      context: ./demo
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgresdb


  frontend: 
    build: 
      context: ./Frontend/VS/react-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
